# Generated by Django 3.2 on 2024-04-20 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vendor_product',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 19, 13, 51, 54112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 19, 13, 51, 55112, tzinfo=utc), verbose_name='Posted Date'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Vendor_Detail',
        ),
        migrations.DeleteModel(
            name='Vendor_Product',
        ),
    ]
