from django.urls import path
from . import views
urlpatterns = [
path('',views.home,name="home"),
path('dashboard/',views.dashboard,name="dashboard"),
path('category/',views.category,name="category"),
path('add_product/',views.add_product,name="add_product"),
path('product_list/',views.product_list,name="product_list"),
path('product_edit/<int:pk>/',views.product_edit,name="product_edit"),
path('product_delete/<int:pk>/',views.product_delete,name="product_delete"),
path('register/',views.register,name="register"),
path('login/', views.user_login, name='user_login'),
path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
path('logout/', views.logout, name='logout'),
path('products/', views.products, name='products'),
path('add_to_cart/<int:pk>/',views.add_to_cart,name="add_to_cart"),
path('view_items_cart_product/',views.view_items_cart_product,name="view_items_cart_product"),
path('remove_item/<int:pk>/',views.remove_item,name="remove_item"),
path('purchase/',views.purchase,name="purchase"),
path('order_item_user/',views.order_item_user,name="order_item_user"),
path('purchased_item/<str:pk>/<str:status>/',views.purchased_item,name="purchased_item"),
path('admin_login/',views.admin_login,name="admin_login"),
path('admin_logout/',views.admin_logout,name="admin_logout"),
path('admin_received_orders/',views.admin_received_orders,name="admin_received_orders"),
path('detail/<str:pk>/',views.detail,name="detail"),
path('payment/<str:pk>/',views.payment,name="payment"),
path('single_product/<int:pk>/',views.single_product,name="single_product"),
path('vendor_login/', views.vendor_login, name='vendor_login'),
path('vendor_dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
path('vendor_logout/', views.vendor_logout, name='vendor_logout'),
path('rise_invoice/<int:pk>/',views.rise_invoice,name="rise_invoice"),
path('invoices/', views.invoices, name='invoices'),
path('add_category/', views.add_category, name='add_category'),
path('lucky_cutomer/', views.lucky_cutomer, name='lucky_cutomer'),
path('stock/', views.stock, name='stock'),

]